services:
  pdftron.pdf_to_xod:
      class: PDFTronBundle\Services\PDFToXODConverter
      arguments: [ '%pdf_tron.options_sets%' ]

  pdftron.crop:
      class: PDFTronBundle\Services\PDFCropper

  pdftron.thumbnail_generator:
        class: PDFTronBundle\Services\PDFThumbnailGenerator

  pdftron.joiner:
      class: PDFTronBundle\Services\PDFJoiner

  pdftron.file_system:
      class: PDFTronBundle\Services\PDFFileSystem
      arguments: [ '%kernel.root_dir%', '%pdf_tron.xod_directory%', '%pdf_tron.xod_directory%', '%pdf_tron.image_directory%' ]

  pdftron.convert_all_command:
      class: PDFTronBundle\Command\ConvertPDFCommand
      arguments: [ '@pdftron.pdf_to_xod', '@pdftron.file_system' ]
      tags:
          - { name: console.command }

  pdftron.crop_command:
      class: PDFTronBundle\Command\CropPDFCommand
      arguments: [ '@pdftron.crop', '@pdftron.file_system' ]
      tags:
          - { name: console.command }